version: "3.8"

volumes:
  db:

services:
  db:
    image: postgres:12.16
    container_name: postgres_for_nextcloud
    restart: unless-stopped
    volumes:
      - db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
    ports:
      - 5432:5432

  adminer:
    image: adminer:4.8.1
    container_name: adminer_for_nextcloud
    restart: unless-stopped
    ports:
      - 81:8080
